# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev_ui/database_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiDBSettingsWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 439)
        Dialog.setMinimumSize(QtCore.QSize(476, 439))
        Dialog.setStyleSheet("#frame {\n"
"    background-color: rgb(0, 1, 171);\n"
"}\n"
"#frame_main {\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"#label_title {\n"
"    font: 9pt \"Flexi IBM VGA False\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QGroupBox {\n"
"    padding-top: 27px;\n"
"    border-style: groove;\n"
"      border-width: 2px;\n"
"      border-top-color: rgb(200, 200, 200);\n"
"      border-left-color: rgb(200, 200, 200);\n"
"      border-right-color: rgb(200, 200, 200);\n"
"      border-bottom-color: rgb(200, 200, 200);\n"
"}\n"
"QGroupBox::title {\n"
"    top: 13px;\n"
"    left: 13px;\n"
" }\n"
"QGroupBox::indicator, QCheckBox::indicator {\n"
"    border-style: groove;\n"
"      border-width: 2px;\n"
"      border-top-color: rgb(100, 100, 100);\n"
"      border-left-color: rgb(100, 100, 100);\n"
"      border-right-color: rgb(200, 200, 200);\n"
"      border-bottom-color: rgb(200, 200, 200);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QGroupBox::indicator:checked, QCheckBox::indicator:checked {\n"
"    image: url(:/icon/resources/icon/check.png);\n"
"}\n"
"\n"
"QListView, QLineEdit { \n"
"    border-style: groove;\n"
"      border-width: 2px;\n"
"      border-top-color: rgb(120, 120, 120);\n"
"      border-left-color: rgb(120, 120, 120);\n"
"      border-right-color: rgb(200, 200, 200);\n"
"      border-bottom-color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:read-only { background-color: rgb(240, 240, 240); }\n"
"\n"
"/*QPUSHBUTTON*/\n"
"QPushButton { \n"
"    border-style: groove;\n"
"      border-width: 2px;\n"
"      border-top-color: rgb(200, 200, 200);\n"
"      border-left-color: rgb(200, 200, 200);\n"
"      border-right-color: rgb(100, 100, 100);\n"
"      border-bottom-color: rgb(100, 100, 100);\n"
"    background-color: rgb(238, 238, 238); \n"
"}\n"
"QPushButton:pressed { \n"
"    background-color: rgb(249, 249, 249);\n"
"    border-style: groove;\n"
"      border-width: 2px;\n"
"      border-top-color: rgb(100, 100, 100);\n"
"      border-left-color: rgb(100, 100, 100);\n"
"      border-right-color: rgb(200, 200, 200);\n"
"      border-bottom-color: rgb(200, 200, 200);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_top)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_close.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_main = QtWidgets.QFrame(self.frame)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_4.setSpacing(11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_SQLite = QtWidgets.QGroupBox(self.frame_main)
        self.groupBox_SQLite.setCheckable(True)
        self.groupBox_SQLite.setChecked(False)
        self.groupBox_SQLite.setObjectName("groupBox_SQLite")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_SQLite)
        self.verticalLayout_6.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout_6.setSpacing(11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_SQLite)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_litePath = QtWidgets.QLineEdit(self.groupBox_SQLite)
        self.lineEdit_litePath.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_litePath.setObjectName("lineEdit_litePath")
        self.horizontalLayout_3.addWidget(self.lineEdit_litePath)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_liteSet = QtWidgets.QPushButton(self.groupBox_SQLite)
        self.pushButton_liteSet.setMinimumSize(QtCore.QSize(85, 25))
        self.pushButton_liteSet.setObjectName("pushButton_liteSet")
        self.horizontalLayout.addWidget(self.pushButton_liteSet)
        self.pushButton_liteCreate = QtWidgets.QPushButton(self.groupBox_SQLite)
        self.pushButton_liteCreate.setMinimumSize(QtCore.QSize(85, 25))
        self.pushButton_liteCreate.setObjectName("pushButton_liteCreate")
        self.horizontalLayout.addWidget(self.pushButton_liteCreate)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_SQLite)
        self.groupBox_MySQL = QtWidgets.QGroupBox(self.frame_main)
        self.groupBox_MySQL.setCheckable(True)
        self.groupBox_MySQL.setChecked(False)
        self.groupBox_MySQL.setObjectName("groupBox_MySQL")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_MySQL)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(11)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_MySQL)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_MySQL)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_MySQL)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_MySQL)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_myHost = QtWidgets.QLineEdit(self.groupBox_MySQL)
        self.lineEdit_myHost.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_myHost.setObjectName("lineEdit_myHost")
        self.gridLayout.addWidget(self.lineEdit_myHost, 0, 1, 1, 1)
        self.lineEdit_myUser = QtWidgets.QLineEdit(self.groupBox_MySQL)
        self.lineEdit_myUser.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_myUser.setObjectName("lineEdit_myUser")
        self.gridLayout.addWidget(self.lineEdit_myUser, 1, 1, 1, 1)
        self.lineEdit_myPassword = QtWidgets.QLineEdit(self.groupBox_MySQL)
        self.lineEdit_myPassword.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_myPassword.setObjectName("lineEdit_myPassword")
        self.gridLayout.addWidget(self.lineEdit_myPassword, 2, 1, 1, 1)
        self.lineEdit_myName = QtWidgets.QLineEdit(self.groupBox_MySQL)
        self.lineEdit_myName.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_myName.setObjectName("lineEdit_myName")
        self.gridLayout.addWidget(self.lineEdit_myName, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox_MySQL)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_main)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_save = QtWidgets.QPushButton(self.frame_main)
        self.pushButton_save.setMinimumSize(QtCore.QSize(85, 25))
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_4.addWidget(self.pushButton_save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.frame_main)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "Настройка базы данных"))
        self.pushButton_close.setText(_translate("Dialog", "X"))
        self.groupBox_SQLite.setTitle(_translate("Dialog", "SQLite"))
        self.label.setText(_translate("Dialog", "Путь:"))
        self.pushButton_liteSet.setText(_translate("Dialog", "Указать"))
        self.pushButton_liteCreate.setText(_translate("Dialog", "Создать"))
        self.groupBox_MySQL.setTitle(_translate("Dialog", "MySQL"))
        self.label_2.setText(_translate("Dialog", "Host:"))
        self.label_5.setText(_translate("Dialog", "Name:"))
        self.label_3.setText(_translate("Dialog", "User:"))
        self.label_4.setText(_translate("Dialog", "Password:"))
        self.label_6.setText(_translate("Dialog", "Не забудь сохранить!"))
        self.pushButton_save.setText(_translate("Dialog", "Сохранить"))
